In [ ]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [5]:
df=pd.read_csv(f"D:\ML\datasets\Heart_Disease_Imbalanced.csv")

In [6]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose,Heart_Rate,Gender,Smoking,Diabetes,Exercise_Level,Family_History,Heart_Disease
0,63,NaN,97.0,127.0,143,90,Male,No,Yes,Low,No,0
1,76,24.9,114.0,147.0,183,62,Female,Yes,No,High,Yes,0
2,53,33.4,NaN,NaN,96,90,Female,No,No,High,No,0
3,39,26.5,155.0,264.0,123,82,Female,No,No,Low,Yes,1
4,67,31.7,168.0,220.0,154,101,Female,No,No,High,No,0

In [7]:
df['Heart_Disease'].value_counts()

Heart_Disease
0    917
1     83
Name: count, dtype: int64

In [10]:
df.isnull().sum()

Age                0
BMI               50
Blood_Pressure    50
Cholesterol       50
Glucose            0
Heart_Rate         0
Gender             0
Smoking           50
Diabetes           0
Exercise_Level    50
Family_History     0
Heart_Disease      0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             1000 non-null   int64
 1   BMI             950 non-null    float64
 2   Blood_Pressure  950 non-null    float64
 3   Cholesterol     950 non-null    float64
 4   Glucose         1000 non-null   int64
 5   Heart_Rate      1000 non-null   int64
 6   Gender          1000 non-null   object
 7   Smoking         950 non-null    object
 8   Diabetes        1000 non-null   object
 9   Exercise_Level  950 non-null    object
 10  Family_History  1000 non-null   object
 11  Heart_Disease   1000 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [18]:
cat_col=df.select_dtypes(include='object').columns
num_col=df.select_dtypes(include='number').columns
df.drop(columns=cat_col).corr()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose,Heart_Rate,Heart_Disease
Age,1.000000,-0.013951,0.020983,-0.005503,0.016906,0.005285,0.022211
BMI,-0.013951,1.000000,-0.068666,0.014276,-0.074897,-0.024099,-0.033310
Blood_Pressure,0.020983,-0.068666,1.000000,0.049352,-0.014336,0.038954,-0.000859
Cholesterol,-0.005503,0.014276,0.049352,1.000000,0.001269,0.018003,-0.044055
Glucose,0.016906,-0.074897,-0.014336,0.001269,1.000000,-0.034927,0.038668
Heart_Rate,0.005285,-0.024099,0.038954,0.018003,-0.034927,1.000000,0.025107
Heart_Disease,0.022211,-0.033310,-0.000859,-0.044055,0.038668,0.025107,1.000000